// <auto-generated />
using System;
using GMP_System.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMP_System.GMP_System.GMP_System.Entities.Migrations
{
    [DbContext(typeof(GmpContext))]
    [Migration("20260428211608_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GMP_System.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PinCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasDefaultValue("000000");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__AppUsers__1788CCAC14F8EE93");

                    b.HasIndex(new[] { "Username" }, "UQ__AppUsers__536C85E4B8A21C8B")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("GMP_System.Entities.BatchProcessLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("BatchID");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    b.Property<bool?>("IsDeviation")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfRouting")
                        .HasColumnType("int");

                    b.Property<int?>("OperatorId")
                        .HasColumnType("int")
                        .HasColumnName("OperatorID");

                    b.Property<string>("ParametersData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("RoutingId")
                        .HasColumnType("int")
                        .HasColumnName("RoutingID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId")
                        .HasName("PK__BatchPro__5E5499A811E7D688");

                    b.HasIndex("BatchId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("OperatorId");

                    b.HasIndex("RoutingId");

                    b.HasIndex("VerifiedById");

                    b.ToTable("BatchProcessLogs", t =>
                        {
                            t.HasTrigger("trg_Check_Equipment_Status");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.BatchProcessParameterValue", b =>
                {
                    b.Property<long>("ValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ValueId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ValueId"));

                    b.Property<decimal?>("ActualValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<long?>("LogId")
                        .HasColumnType("bigint")
                        .HasColumnName("LogId");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParameterId")
                        .HasColumnType("int")
                        .HasColumnName("ParameterId");

                    b.Property<DateTime?>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ValueId");

                    b.HasIndex("LogId");

                    b.HasIndex("ParameterId");

                    b.ToTable("BatchProcessParameterValues");
                });

            modelBuilder.Entity("GMP_System.Entities.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EquipmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    b.Property<string>("EquipmentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TechnicalSpecification")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UsagePurpose")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("EquipmentId")
                        .HasName("PK__Equipmen__34474599F11FEE84");

                    b.HasIndex("AreaId");

                    b.HasIndex(new[] { "EquipmentCode" }, "UQ__Equipmen__09E4417E23FBF8F4")
                        .IsUnique();

                    b.ToTable("Equipments", t =>
                        {
                            t.HasTrigger("trg_Audit_Equipments");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.InventoryLot", b =>
                {
                    b.Property<int>("LotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LotId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LotId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialId");

                    b.Property<string>("QCStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("QCStatus");

                    b.Property<decimal>("QuantityCurrent")
                        .HasColumnType("decimal(18, 4)")
                        .HasColumnName("QuantityCurrent");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LotId");

                    b.HasIndex("MaterialId");

                    b.ToTable("InventoryLots", t =>
                        {
                            t.HasTrigger("trg_Audit_InventoryLots");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialId"));

                    b.Property<int?>("BaseUomId")
                        .HasColumnType("int")
                        .HasColumnName("BaseUomID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TechnicalSpecification")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("TechnicalSpecification");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MaterialId")
                        .HasName("PK__Material__C50613177C517D7B");

                    b.HasIndex("BaseUomId");

                    b.HasIndex(new[] { "MaterialCode" }, "UQ__Material__170C54BAB161407D")
                        .IsUnique();

                    b.ToTable("Materials", t =>
                        {
                            t.HasTrigger("trg_Audit_Materials");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.MaterialUsage", b =>
                {
                    b.Property<int>("UsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsageId"));

                    b.Property<decimal>("ActualAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("BatchId")
                        .HasColumnType("int")
                        .HasColumnName("BatchID");

                    b.Property<int?>("DispensedBy")
                        .HasColumnType("int");

                    b.Property<int?>("InventoryLotId")
                        .HasColumnType("int")
                        .HasColumnName("InventoryLotID");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PlannedAmount")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UsedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UsageId")
                        .HasName("PK__Material__29B197C0A60A3ED1");

                    b.HasIndex("BatchId");

                    b.HasIndex("DispensedBy");

                    b.HasIndex("InventoryLotId");

                    b.ToTable("MaterialUsage", null, t =>
                        {
                            t.HasTrigger("trg_Check_Material_QC");

                            t.HasTrigger("trg_Validate_Material_Usage");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionArea", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AreaId")
                        .HasName("PK__Producti__70B82028");

                    b.HasIndex(new[] { "AreaCode" }, "UQ_ProductionAreas_AreaCode")
                        .IsUnique();

                    b.ToTable("ProductionAreas", (string)null);
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BatchID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManufactureDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<decimal?>("PlannedQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Queued");

                    b.HasKey("BatchId")
                        .HasName("PK__Producti__5D55CE38408FD6AE");

                    b.HasIndex("OrderId");

                    b.HasIndex(new[] { "BatchNumber" }, "UQ__Producti__F869ED6D7BFC6457")
                        .IsUnique();

                    b.ToTable("ProductionBatches");
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<decimal?>("ActualQuantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("PlannedCartons")
                        .HasColumnType("int");

                    b.Property<decimal>("PlannedQuantity")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipeID");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId")
                        .HasName("PK__Producti__C3905BAF770F7793");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RecipeId");

                    b.HasIndex(new[] { "OrderCode" }, "UQ__Producti__999B5229EBD49113")
                        .IsUnique();

                    b.ToTable("ProductionOrders", t =>
                        {
                            t.HasTrigger("trg_Audit_ProductionOrders");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RecipeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("BatchSize")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("RecipeId")
                        .HasName("PK__Recipes__FDD988D03D4E35FD");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex(new[] { "MaterialId", "VersionNumber" }, "UQ_Recipe_Version")
                        .IsUnique()
                        .HasFilter("[MaterialID] IS NOT NULL");

                    b.ToTable("Recipes", t =>
                        {
                            t.HasTrigger("trg_Prevent_Edit_Approved_Recipe");

                            t.HasTrigger("trg_Recipes_Audit");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("GMP_System.Entities.RecipeBom", b =>
                {
                    b.Property<int>("BomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BomId"));

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("MaterialID");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipeID");

                    b.Property<int?>("UomId")
                        .HasColumnType("int")
                        .HasColumnName("UomID");

                    b.Property<decimal?>("WastePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("BomId")
                        .HasName("PK__RecipeBO__7D5F6A17C1D35BE0");

                    b.HasIndex("MaterialId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UomId");

                    b.ToTable("RecipeBOM", (string)null);
                });

            modelBuilder.Entity("GMP_System.Entities.RecipeRouting", b =>
                {
                    b.Property<int>("RoutingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoutingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoutingId"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("CleanlinessStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DefaultEquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("DefaultEquipmentID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfRouting")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("RecipeID");

                    b.Property<decimal?>("SetTemperature")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SetTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("StabilityStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardHumidity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardPressure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardTemperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("RoutingId")
                        .HasName("PK__RecipeRo__A763F8A8F9EEA6DD");

                    b.HasIndex("AreaId");

                    b.HasIndex("DefaultEquipmentId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrderId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeRouting", (string)null);
                });

            modelBuilder.Entity("GMP_System.Entities.StepParameter", b =>
                {
                    b.Property<int>("ParameterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ParameterId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParameterId"));

                    b.Property<bool?>("IsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RoutingId")
                        .HasColumnType("int")
                        .HasColumnName("RoutingId");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParameterId");

                    b.HasIndex("RoutingId");

                    b.ToTable("StepParameters");
                });

            modelBuilder.Entity("GMP_System.Entities.UnitOfMeasure", b =>
                {
                    b.Property<int>("UomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UomID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UomId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UomId")
                        .HasName("PK__UnitOfMe__F6F8D59EA16C24B6");

                    b.ToTable("UnitOfMeasure", (string)null);
                });

            modelBuilder.Entity("GMP_System.Entities.UomConversion", b =>
                {
                    b.Property<int>("ConversionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ConversionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversionId"));

                    b.Property<decimal>("ConversionFactor")
                        .HasColumnType("decimal(18, 6)")
                        .HasColumnName("ConversionFactor");

                    b.Property<int?>("FromUomId")
                        .HasColumnType("int")
                        .HasColumnName("FromUomID");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ToUomId")
                        .HasColumnType("int")
                        .HasColumnName("ToUomID");

                    b.HasKey("ConversionId")
                        .HasName("PK__UomConve__A7A07F935A520669");

                    b.HasIndex("ToUomId");

                    b.HasIndex(new[] { "FromUomId", "ToUomId" }, "UQ_Conversion")
                        .IsUnique()
                        .HasFilter("[FromUomID] IS NOT NULL AND [ToUomID] IS NOT NULL");

                    b.ToTable("UomConversions");
                });

            modelBuilder.Entity("GMP_System.Entities.BatchProcessLog", b =>
                {
                    b.HasOne("GMP_System.Entities.ProductionBatch", "Batch")
                        .WithMany("BatchProcessLogs")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__BatchProc__Batch__7C4F7684");

                    b.HasOne("GMP_System.Entities.Equipment", "Equipment")
                        .WithMany("BatchProcessLogs")
                        .HasForeignKey("EquipmentId")
                        .HasConstraintName("FK__BatchProc__Equip__7E37BEF6");

                    b.HasOne("GMP_System.Entities.AppUser", "Operator")
                        .WithMany("BatchProcessLogOperators")
                        .HasForeignKey("OperatorId")
                        .HasConstraintName("FK_BatchProcessLog_Operator");

                    b.HasOne("GMP_System.Entities.RecipeRouting", "Routing")
                        .WithMany("BatchProcessLogs")
                        .HasForeignKey("RoutingId")
                        .HasConstraintName("FK__BatchProc__Routi__7D439ABD");

                    b.HasOne("GMP_System.Entities.AppUser", "VerifiedBy")
                        .WithMany("BatchProcessLogVerifiers")
                        .HasForeignKey("VerifiedById")
                        .HasConstraintName("FK_BatchProcessLog_Verifier");

                    b.Navigation("Batch");

                    b.Navigation("Equipment");

                    b.Navigation("Operator");

                    b.Navigation("Routing");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("GMP_System.Entities.BatchProcessParameterValue", b =>
                {
                    b.HasOne("GMP_System.Entities.BatchProcessLog", "Log")
                        .WithMany("ParameterValues")
                        .HasForeignKey("LogId")
                        .HasConstraintName("FK_ParamValue_Log");

                    b.HasOne("GMP_System.Entities.StepParameter", "Parameter")
                        .WithMany("ParameterValues")
                        .HasForeignKey("ParameterId")
                        .HasConstraintName("FK_ParamValue_Parameter");

                    b.Navigation("Log");

                    b.Navigation("Parameter");
                });

            modelBuilder.Entity("GMP_System.Entities.Equipment", b =>
                {
                    b.HasOne("GMP_System.Entities.ProductionArea", "Area")
                        .WithMany("Equipments")
                        .HasForeignKey("AreaId")
                        .HasConstraintName("FK_Equipments_ProductionAreas");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("GMP_System.Entities.InventoryLot", b =>
                {
                    b.HasOne("GMP_System.Entities.Material", "Material")
                        .WithMany("InventoryLots")
                        .HasForeignKey("MaterialId");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("GMP_System.Entities.Material", b =>
                {
                    b.HasOne("GMP_System.Entities.UnitOfMeasure", "BaseUom")
                        .WithMany("Materials")
                        .HasForeignKey("BaseUomId")
                        .HasConstraintName("FK__Materials__BaseU__4E88ABD4");

                    b.Navigation("BaseUom");
                });

            modelBuilder.Entity("GMP_System.Entities.MaterialUsage", b =>
                {
                    b.HasOne("GMP_System.Entities.ProductionBatch", "Batch")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("BatchId")
                        .HasConstraintName("FK__MaterialU__Batch__05D8E0BE");

                    b.HasOne("GMP_System.Entities.AppUser", "DispensedByNavigation")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("DispensedBy")
                        .HasConstraintName("FK_Usage_User");

                    b.HasOne("GMP_System.Entities.InventoryLot", "InventoryLot")
                        .WithMany("MaterialUsages")
                        .HasForeignKey("InventoryLotId")
                        .HasConstraintName("FK__MaterialU__Inven__06CD04F7");

                    b.Navigation("Batch");

                    b.Navigation("DispensedByNavigation");

                    b.Navigation("InventoryLot");
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionBatch", b =>
                {
                    b.HasOne("GMP_System.Entities.ProductionOrder", "Order")
                        .WithMany("ProductionBatches")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK__Productio__Order__76969D2E");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionOrder", b =>
                {
                    b.HasOne("GMP_System.Entities.AppUser", "CreatedByNavigation")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Orders_User");

                    b.HasOne("GMP_System.Entities.Recipe", "Recipe")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("FK__Productio__Recip__70DDC3D8");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GMP_System.Entities.Recipe", b =>
                {
                    b.HasOne("GMP_System.Entities.AppUser", "ApprovedByNavigation")
                        .WithMany("Recipes")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_Recipes_User");

                    b.HasOne("GMP_System.Entities.Material", "Material")
                        .WithMany("Recipes")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__Recipes__Materia__628FA481");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("GMP_System.Entities.RecipeBom", b =>
                {
                    b.HasOne("GMP_System.Entities.Material", "Material")
                        .WithMany("RecipeBoms")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("FK__RecipeBOM__Mater__6754599E");

                    b.HasOne("GMP_System.Entities.Recipe", "Recipe")
                        .WithMany("RecipeBoms")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("FK__RecipeBOM__Recip__66603565");

                    b.HasOne("GMP_System.Entities.UnitOfMeasure", "Uom")
                        .WithMany("RecipeBoms")
                        .HasForeignKey("UomId")
                        .HasConstraintName("FK__RecipeBOM__UomID__68487DD7");

                    b.Navigation("Material");

                    b.Navigation("Recipe");

                    b.Navigation("Uom");
                });

            modelBuilder.Entity("GMP_System.Entities.RecipeRouting", b =>
                {
                    b.HasOne("GMP_System.Entities.ProductionArea", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.HasOne("GMP_System.Entities.Equipment", "DefaultEquipment")
                        .WithMany("RecipeRoutings")
                        .HasForeignKey("DefaultEquipmentId")
                        .HasConstraintName("FK__RecipeRou__Defau__6D0D32F4");

                    b.HasOne("GMP_System.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.HasOne("GMP_System.Entities.ProductionOrder", "Order")
                        .WithMany("RecipeRoutings")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_RecipeRouting_ProductionOrders");

                    b.HasOne("GMP_System.Entities.Recipe", "Recipe")
                        .WithMany("RecipeRoutings")
                        .HasForeignKey("RecipeId")
                        .HasConstraintName("FK__RecipeRou__Recip__6C190EBB");

                    b.Navigation("Area");

                    b.Navigation("DefaultEquipment");

                    b.Navigation("Material");

                    b.Navigation("Order");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("GMP_System.Entities.StepParameter", b =>
                {
                    b.HasOne("GMP_System.Entities.RecipeRouting", "Routing")
                        .WithMany("StepParameters")
                        .HasForeignKey("RoutingId")
                        .HasConstraintName("FK_StepParameter_Routing");

                    b.Navigation("Routing");
                });

            modelBuilder.Entity("GMP_System.Entities.UomConversion", b =>
                {
                    b.HasOne("GMP_System.Entities.UnitOfMeasure", "FromUom")
                        .WithMany("UomConversionFromUoms")
                        .HasForeignKey("FromUomId")
                        .HasConstraintName("FK__UomConver__FromU__5DCAEF64");

                    b.HasOne("GMP_System.Entities.UnitOfMeasure", "ToUom")
                        .WithMany("UomConversionToUoms")
                        .HasForeignKey("ToUomId")
                        .HasConstraintName("FK__UomConver__ToUom__5EBF139D");

                    b.Navigation("FromUom");

                    b.Navigation("ToUom");
                });

            modelBuilder.Entity("GMP_System.Entities.AppUser", b =>
                {
                    b.Navigation("BatchProcessLogOperators");

                    b.Navigation("BatchProcessLogVerifiers");

                    b.Navigation("MaterialUsages");

                    b.Navigation("ProductionOrders");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("GMP_System.Entities.BatchProcessLog", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("GMP_System.Entities.Equipment", b =>
                {
                    b.Navigation("BatchProcessLogs");

                    b.Navigation("RecipeRoutings");
                });

            modelBuilder.Entity("GMP_System.Entities.InventoryLot", b =>
                {
                    b.Navigation("MaterialUsages");
                });

            modelBuilder.Entity("GMP_System.Entities.Material", b =>
                {
                    b.Navigation("InventoryLots");

                    b.Navigation("RecipeBoms");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionArea", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionBatch", b =>
                {
                    b.Navigation("BatchProcessLogs");

                    b.Navigation("MaterialUsages");
                });

            modelBuilder.Entity("GMP_System.Entities.ProductionOrder", b =>
                {
                    b.Navigation("ProductionBatches");

                    b.Navigation("RecipeRoutings");
                });

            modelBuilder.Entity("GMP_System.Entities.Recipe", b =>
                {
                    b.Navigation("ProductionOrders");

                    b.Navigation("RecipeBoms");

                    b.Navigation("RecipeRoutings");
                });

            modelBuilder.Entity("GMP_System.Entities.RecipeRouting", b =>
                {
                    b.Navigation("BatchProcessLogs");

                    b.Navigation("StepParameters");
                });

            modelBuilder.Entity("GMP_System.Entities.StepParameter", b =>
                {
                    b.Navigation("ParameterValues");
                });

            modelBuilder.Entity("GMP_System.Entities.UnitOfMeasure", b =>
                {
                    b.Navigation("Materials");

                    b.Navigation("RecipeBoms");

                    b.Navigation("UomConversionFromUoms");

                    b.Navigation("UomConversionToUoms");
                });
#pragma warning restore 612, 618
        }
    }
}
